const departamentos = [
    { id: 1, nombre: "Amazonas" },
    { id: 2, nombre: "Antioquia" },
    { id: 3, nombre: "Arauca" },
    { id: 4, nombre: "Atlántico" },
    { id: 5, nombre: "Bolívar" },
    { id: 6, nombre: "Boyacá" },
    { id: 7, nombre: "Caldas" },
    { id: 8, nombre: "Caquetá" },
    { id: 9, nombre: "Casanare" },
    { id: 10, nombre: "Cauca" },
    { id: 11, nombre: "Cesar" },
    { id: 12, nombre: "Chocó" },
    { id: 13, nombre: "Cundinamarca" },
    { id: 14, nombre: "Córdoba" },
    { id: 15, nombre: "Guainía" },
    { id: 16, nombre: "Guaviare" },
    { id: 17, nombre: "Huila" },
    { id: 18, nombre: "La Guajira" },
    { id: 19, nombre: "Magdalena" },
    { id: 20, nombre: "Meta" },
    { id: 21, nombre: "Nariño" },
    { id: 22, nombre: "Norte de Santander" },
    { id: 23, nombre: "Putumayo" },
    { id: 24, nombre: "Quindío" },
    { id: 25, nombre: "Risaralda" },
    { id: 26, nombre: "San Andrés, Providencia y Santa Catalina" },
    { id: 27, nombre: "Santander" },
    { id: 28, nombre: "Sucre" },
    { id: 29, nombre: "Tolima" },
    { id: 30, nombre: "Valle del Cauca" },
    { id: 31, nombre: "Vaupés" },
    { id: 32, nombre: "Vichada" },
];

const ciudades = [
    { id: 1, nombre: "Arauca", dpto: 3},
    { id: 2, nombre: "Armenia", dpto: 24},
    { id: 3, nombre: "Barranquilla", dpto: 4},
    { id: 4, nombre: "Bogotá", dpto: 13},
    { id: 5, nombre: "Bucaramanga", dpto: 27},
    { id: 6, nombre: "Cali", dpto: 30},
    { id: 7, nombre: "Cartagena", dpto: 5},
    { id: 8, nombre: "Cúcuta", dpto: 22},
    { id: 9, nombre: "Florencia", dpto: 8},
    { id: 10, nombre: "Ibagué", dpto: 29},
    { id: 11, nombre: "Leticia", dpto: 1},
    { id: 12, nombre: "Manizales", dpto: 7},
    { id: 13, nombre: "Medellín", dpto: 2},
    { id: 14, nombre: "Mitú", dpto: 31},
    { id: 15, nombre: "Mocoa", dpto: 23},
    { id: 16, nombre: "Montería", dpto: 14},
    { id: 17, nombre: "Neiva", dpto: 17},
    { id: 18, nombre: "Pasto", dpto: 21},
    { id: 19, nombre: "Pereira", dpto: 25},
    { id: 20, nombre: "Popayán", dpto: 10},
    { id: 21, nombre: "Puerto Carreño", dpto: 32},
    { id: 22, nombre: "Puerto Inírida", dpto: 15},
    { id: 23, nombre: "Quibdó", dpto: 12},
    { id: 24, nombre: "Riohacha", dpto: 18},
    { id: 25, nombre: "San Andrés", dpto: 26},
    { id: 26, nombre: "San José del Guaviare", dpto: 16},
    { id: 27, nombre: "Santa Marta", dpto: 19},
    { id: 28, nombre: "Sincelejo", dpto: 28},
    { id: 29, nombre: "Tunja", dpto: 6},
    { id: 30, nombre: "Valledupar", dpto: 11},
    { id: 31, nombre: "Villavicencio", dpto: 20},
    { id: 32, nombre: "Yopal", dpto: 9},
];


